### ISSUE TITLE
Request for License Compliance

### ISSUE THREAD

**Issue by shiena** [WaGi-Coding/OpenXR-Runtime-Switcher#3]
I'm @shiena, the owner of [OpenXRRuntimeSelector](https://github.com/shiena/OpenXRRuntimeSelector), where I've released code under the MIT License.

Recently, I've noticed a similarity in this repository that suggests it might be based on my source code. This leads me to believe that my code has been reused.

While I appreciate the reuse under the MIT License, removing the license text constitutes a violation. Therefore, if you have indeed reused my code, I kindly ask you to add the original license text.

**Comment by WaGi-Coding** [comment]
i might most likely have iirc for the runtimes detection part, added you to
the license, check if thats fine, never dealt with such case ^^
https://github.com/WaGi-Coding/OpenXR-Runtime-Switcher/commit/f2df0fdbcbfda350d141a909037460923e2aa748

Have a nice day

**Comment by shiena** [comment]
Thank you for adding the license.
